# Generated by Django 5.0.3 on 2024-03-12 16:09

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('post_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Обложка')),
                ('text', models.TextField(verbose_name='Содержимое')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('action', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_post', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ManyToManyField(related_name='post_category', to='news.category', verbose_name='Категория')),
                ('tag', models.ManyToManyField(related_name='post_tag', to='news.posttag', verbose_name='Тег')),
            ],
        ),
    ]
