# Generated by Django 5.0.3 on 2024-03-19 09:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('post_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(default=None, upload_to='news/%Y/%m/%d/', verbose_name='Обложка')),
                ('text', models.TextField(verbose_name='Содержимое')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
                ('tag_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
