# Generated by Django 5.0.3 on 2024-03-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='news/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
