# Generated by Django 5.0.3 on 2024-03-19 09:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_name_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='posttag',
            name='tag_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
    ]
