# Generated by Django 5.0.3 on 2024-03-19 09:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_category_slug_posttag_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tag_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
    ]
