# Generated by Django 5.0.1 on 2024-01-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('author_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Автор оригинала',
                'verbose_name_plural': 'Авторы оригиналов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
                ('genre_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('producer_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Seiyuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('seiyuu_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Сейю',
                'verbose_name_plural': 'Сейю',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('studio_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Teг')),
                ('tag_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(default=2000, verbose_name='Год издания')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
                'ordering': ('years',),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.TextField()),
                ('seiyuu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='anime.seiyuu', verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Заголовок на русском')),
                ('name_en', models.CharField(max_length=255, verbose_name='Заголовок на английском')),
                ('name_jp', models.CharField(max_length=255, verbose_name='Заголовок на японском')),
                ('episodes', models.IntegerField(default=1, verbose_name='Количество эпизодов')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='anime.author', verbose_name='Автор оригинала')),
                ('genre', models.ManyToManyField(related_name='genre', to='anime.genre', verbose_name='Жанр')),
                ('producer', models.ManyToManyField(related_name='producer', to='anime.producer', verbose_name='Режиссер')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='anime.studio', verbose_name='Студия-издатель')),
                ('tag', models.ManyToManyField(related_name='tags', to='anime.tag', verbose_name='Теги')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='year', to='anime.years', verbose_name='Год выхода')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ('name_ru',),
            },
        ),
    ]
