# Generated by Django 5.0.3 on 2024-03-19 09:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Заголовок на русском')),
                ('name_en', models.CharField(max_length=255, verbose_name='Заголовок на английском')),
                ('name_jp', models.CharField(max_length=255, verbose_name='Заголовок на японском')),
                ('anime_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name_jp', unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Обложка')),
                ('episodes', models.IntegerField(default=1, verbose_name='Количество эпизодов')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ('name_ru',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('author_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Автор оригинала',
                'verbose_name_plural': 'Авторы оригиналов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('description', models.TextField()),
                ('character_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
                ('genre_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('producer_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Seiyuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('seiyuu_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Сейю',
                'verbose_name_plural': 'Сейю',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('studio_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг')),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Teг')),
                ('tag_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='tag', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, verbose_name='Год издания')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
                'ordering': ('year',),
            },
        ),
    ]
