# Generated by Django 5.0.1 on 2024-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
