# Generated by Django 4.1 on 2024-03-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='years',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_year', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='tag',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_tag', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='studio',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_studio', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='seiyuu',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_seiyuu', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='producer',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_producer', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='genre',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_genre', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='character',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_character', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='character',
            name='seiyuu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.seiyuu', verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='author',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_author', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='anime',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_anime', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='anime',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='anime.author', verbose_name='Автор оригинала'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='anime.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='producer', to='anime.producer', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(related_name='studio', to='anime.studio', verbose_name='Студия-издатель'),
        ),
        migrations.AddField(
            model_name='anime',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='anime.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='anime.years', verbose_name='Год выхода'),
        ),
    ]
