# Generated by Django 5.0.1 on 2024-01-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('name_ru',), 'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',), 'verbose_name': 'Автор оригинала', 'verbose_name_plural': 'Авторы оригиналов'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('name',), 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ('name',), 'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='seiyuu',
            options={'ordering': ('name',), 'verbose_name': 'Сейю', 'verbose_name_plural': 'Сейю'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ('name',), 'verbose_name': 'Студия', 'verbose_name_plural': 'Студии'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='years',
            options={'ordering': ('years',), 'verbose_name': 'Год', 'verbose_name_plural': 'Годы'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='anime.author', verbose_name='Автор оригинала'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=1, verbose_name='Количество эпизодов'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(related_name='genre', through='anime.AnimeGenreTable', to='anime.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Заголовок на английском'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name_jp',
            field=models.CharField(max_length=255, verbose_name='Заголовок на японском'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Заголовок на русском'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='producer',
            field=models.ManyToManyField(related_name='producer', through='anime.AnimeProducerTable', to='anime.producer', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='anime.studio', verbose_name='Студия-издатель'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='tag',
            field=models.ManyToManyField(related_name='tags', through='anime.AnimeTagTable', to='anime.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='year', to='anime.years', verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='character',
            name='seiyuu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='anime.seiyuu', verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='seiyuu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='seiyuu',
            name='seiyuu_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Teг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='years',
            name='years',
            field=models.IntegerField(default=2000, verbose_name='Год издания'),
        ),
    ]
