# Generated by Django 5.0.1 on 2024-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_character_character_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(null=True, related_name='studio', to='anime.studio', verbose_name='Студия-издатель'),
        ),
    ]
