# Generated by Django 5.0.1 on 2024-01-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_studio_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(related_name='studio', to='anime.studio', verbose_name='Студия-издатель'),
        ),
    ]
