# Generated by Django 5.0.1 on 2024-01-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year', to='anime.years', verbose_name='Год выхода'),
        ),
    ]
