# Generated by Django 5.0.1 on 2024-01-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='character',
            name='seiyuu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.seiyuu', verbose_name='Слаг'),
        ),
    ]
