# Generated by Django 5.0.1 on 2024-02-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_producer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='years',
            options={'ordering': ('year',), 'verbose_name': 'Год', 'verbose_name_plural': 'Годы'},
        ),
        migrations.RenameField(
            model_name='years',
            old_name='years',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='anime.years', verbose_name='Год выхода'),
        ),
    ]
