# Generated by Django 5.0.1 on 2024-02-13 12:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_years_options_rename_years_years_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name_jp', verbose_name='Слаг'),
        ),
    ]
