# Generated by Django 5.0.1 on 2024-02-13 13:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name_jp', unique=True, verbose_name='Слаг'),
        ),
    ]
