# Generated by Django 5.0.1 on 2024-02-13 13:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
    ]
