# Generated by Django 5.0.1 on 2024-02-13 13:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_alter_genre_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='seiyuu',
            name='seiyuu_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='tag', unique=True, verbose_name='Слаг'),
        ),
    ]
