# Generated by Django 5.0.1 on 2024-02-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_author_author_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='slug',
            new_name='anime_slug',
        ),
    ]
