# Generated by Django 4.1 on 2024-02-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_anime_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='photo',
            new_name='image',
        ),
    ]
