# Generated by Django 4.1 on 2024-02-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_rename_photo_anime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
