# Generated by Django 4.1 on 2024-02-21 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0017_anime_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='added',
        ),
        migrations.AddField(
            model_name='anime',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_anime', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='author',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_author', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='character',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_character', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='genre',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_genre', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='producer',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_producer', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='seiyuu',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_seiyuu', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='studio',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_studio', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='tag',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_tag', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='years',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_year', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
    ]
