# Generated by Django 4.1 on 2024-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_remove_anime_added_anime_action_author_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo/%Y/%m/%d/', verbose_name='Логотип'),
        ),
    ]
