# Generated by Django 4.1 on 2024-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_studio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='logo',
            field=models.ImageField(upload_to='logo/%Y/%m/%d/', verbose_name='Логотип'),
        ),
    ]
